### ISSUE TITLE
荣耀V9能否使用？

### ISSUE THREAD

**Issue by Sdarfeesh** [Coconutat/android_kernel_huawei_vtr_emui9_KernelSU#1]

**Comment by Coconutat** [comment]
不能，我没有添加荣耀的部分。最近会研究一下，但不能保证成功，因为手头没有荣耀。

**Comment by Coconutat** [comment]
> _No description provided._

我目前编译了一个，需要你自行测试，记得备份原来的内核。下载地址：https://wwcy.lanzoum.com/iht1X0rqwyuf
