### ISSUE TITLE
内核在android13 gsi上无法启动

### ISSUE THREAD

**Issue by imlaoyou2333** [Coconutat/android_kernel_huawei_vtr_emui9_KernelSU#2]
手机型号 P10 VTR-AL00
刷入内核后启动进入recovery
gsi: naz的crdroid 9.2

**Comment by Coconutat** [comment]
> 手机型号 P10 VTR-AL00 刷入内核后启动进入recovery gsi: naz的crdroid 9.2
这个有可能是GSI的问题，并非一定是内核的问题。
AndyYan的LineageSO 20.0 GSI刷入我也不开机。换老版本内核也一样。你可以先排查下。

**Comment by imlaoyou2333** [comment]
好像是系统不能在宽容模式的selinux启动，刷入了非宽容模式的盘古内核就成功开机了

**Comment by Coconutat** [comment]
> 好像是系统不能在宽容模式的selinux启动，刷入了非宽容模式的盘古内核就成功开机了

目前内核无法强制SELinux模式，强制会导致KernelSU失效。我目前没有解决方案。

**Comment by imlaoyou2333** [comment]
nazim最新的[crdroid9.3](https://github.com/naz664/crDroid_gsi)可以启动了

**Comment by Coconutat** [comment]
> nazim最新的[crdroid9.3](https://github.com/naz664/crDroid_gsi)可以启动了 ~但是存储空间离奇消失了~格式化一下就好了

建议你配合最新的KernelSU内核和KernelSU管理器。修复了ZygiskOnKernelSU和LSposed不生效的问题。如果不生效建议你反馈KernelSU官方（因为模块挂载生效这个不是我能修改的，需要社区讨论）。
