### ISSUE TITLE
Android 13 gsi 上的内核损坏

### ISSUE THREAD

**Issue by CidKagenouShadow** [Coconutat/android_kernel_huawei_vtr_emui9_KernelSU#3]
内核破坏了安全性，导致无法在 android 13 gsi 上启动

这解决了构建内核时的问题

https://lore.kernel.org/lkml/20190114171021.86171-1-tkjos@google.com/

**Comment by Coconutat** [comment]
> 内核破坏了安全性，导致无法在 android 13 gsi 上启动
> 
> 这解决了构建内核时的问题
> 
> https://lore.kernel.org/lkml/20190114171021.86171-1-tkjos@google.com/

描述下具体的问题，如果指SELinux的问题，欢迎你Pull Requests

**Comment by CidKagenouShadow** [comment]
问题不涉及selinux，只是内核缺少update binder

phhusson 说补丁解决了 android 13 gsi 的启动问题
