### ISSUE TITLE
没有issue，纯粹是激动得想聊天，看到就close掉吧

### ISSUE THREAD

**Issue by maimaiguanfan** [Coconutat/android_kernel_huawei_vtr_emui9_KernelSU#5]
今晚刚想搞搞盘古内核的kernel su，去翻官方文档，查到已经有人搞好了p20lite

https://kernelsu.org/zh_CN/guide/unofficially-support-devices.html

我擦，居然有大佬还在搞华为，我都已经已经灭绝了，这个内核版本正好是4.9的，那我不得去拉个commit，直接编译躺赢

然后去查了那个内核，发现居然有pull request，就顺藤摸瓜找到了这里

然后发现，这个内核居然是基于盘古内核搞的，我擦，盘古内核，那可是天下第一无敌牛逼超级厉害帅的一批的麦麦观饭开发的内核😅😅（开个玩笑）

大哥玩不玩QQ，有没有进千雪乃月或者kindle4jerry的群，感觉可以交流一波

794133217
645017593

**Comment by Coconutat** [comment]
> 今晚刚想搞搞盘古内核的kernel su，去翻官方文档，查到已经有人搞好了p20lite
> 
> https://kernelsu.org/zh_CN/guide/unofficially-support-devices.html
> 
> 我擦，居然有大佬还在搞华为，我都已经已经灭绝了，这个内核版本正好是4.9的，那我不得去拉个commit，直接编译躺赢
> 
> 然后去查了那个内核，发现居然有pull request，就顺藤摸瓜找到了这里
> 
> 然后发现，这个内核居然是基于盘古内核搞的，我擦，盘古内核，那可是天下第一无敌牛逼超级厉害帅的一批的麦麦观饭开发的内核😅😅（开个玩笑）
> 
> 大哥玩不玩QQ，有没有进千雪乃月或者kindle4jerry的群，感觉可以交流一波
> 
> 794133217 645017593

我其实加了第一个，第二个也可以加。（滑稽）欢迎大佬过来交流。^v^
