### ISSUE TITLE
Device shuts down on reboot

### ISSUE THREAD

**Issue by vGreatDragon** [Coconutat/android_kernel_huawei_vtr_emui9_KernelSU#6]
Device: Huawei Nova 2s hi3660
OS: EMUI-9.0, Treble Generic A13
Kernel version 4.9.113 KSU _V9

After installing any first module, the reboot is successful, all subsequent reboots are forced, or the device simply turns off. At the same time, the installed modules work properly. Another feature, this is only observed on Treble firmware, on EMUI-9 stock all reboots work properly.
twrp your installed huawei-vtr-al00-em9_0-twrp3.2.3-7to-recovery-9.4.2
[kernel1_log.txt](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/files/12343823/kernel1_log.txt)
[recovery.log](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/files/12343824/recovery.log)
[dmesg.log](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/files/12343825/dmesg.log)

**Comment by Coconutat** [comment]
> Device: Huawei Nova 2s hi3660 OS: EMUI-9.0, Treble Generic A13 Kernel version 4.9.113 KSU _V9
> 
> After installing any first module, the reboot is successful, all subsequent reboots are forced, or the device simply turns off. At the same time, the installed modules work properly. Another feature, this is only observed on Treble firmware, on EMUI-9 stock all reboots work properly. twrp your installed huawei-vtr-al00-em9_0-twrp3.2.3-7to-recovery-9.4.2 [kernel1_log.txt](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/files/12343823/kernel1_log.txt) [recovery.log](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/files/12343824/recovery.log) [dmesg.log](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/files/12343825/dmesg.log)

I uploaded twrp Recovery is not really for your device.Only Support VTR（P10）.
So,I think you need find Nova 2S Version TWRP.
FOR GSI A13,I need do some research.

**Comment by Coconutat** [comment]
> Device: Huawei Nova 2s hi3660 OS: EMUI-9.0, Treble Generic A13 Kernel version 4.9.113 KSU _V9
> 
> After installing any first module, the reboot is successful, all subsequent reboots are forced, or the device simply turns off. At the same time, the installed modules work properly. Another feature, this is only observed on Treble firmware, on EMUI-9 stock all reboots work properly. twrp your installed huawei-vtr-al00-em9_0-twrp3.2.3-7to-recovery-9.4.2 [kernel1_log.txt](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/files/12343823/kernel1_log.txt) [recovery.log](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/files/12343824/recovery.log) [dmesg.log](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/files/12343825/dmesg.log)

And,What module did you install in A13 GSI？I found some Selinux denied in log.

**Comment by vGreatDragon** [comment]
Thanks for reaching out to help me figure out this issue. Unfortunately I don't have TWRP for my device on 9.0, but yours works great and does all its functions. I indicated above, on the stock firmware, there is no such problem, your kernel + your TWRP device reboots without problems, this only happens on GSI firmware .. I tried all the kernel options, installed TWRP in eRecovery and installed the stock recovery in place, the problem remains.

**Comment by vGreatDragon** [comment]
You put any first module, any, the device reboots normally .. And then there is a problem, with any reboot. At the same time, the device remembers the last task: I give the reboot command in recovery, it turns off, just turn it on, it goes into recovery ..

**Comment by Coconutat** [comment]
> You put any first module, any, the device reboots normally .. And then there is a problem, with any reboot. At the same time, the device remembers the last task: I give the reboot command in recovery, it turns off, just turn it on, it goes into recovery ..

Only on GSI,this mean it's probably is GSI bugs.But still,I will found some solution.

**Comment by Coconutat** [comment]
> Thanks for reaching out to help me figure out this issue. Unfortunately I don't have TWRP for my device on 9.0, but yours works great and does all its functions. I indicated above, on the stock firmware, there is no such problem, your kernel + your TWRP device reboots without problems, this only happens on GSI firmware .. I tried all the kernel options, installed TWRP in eRecovery and installed the stock recovery in place, the problem remains.

maybe you can try use the permissive version kernel.And watch it will be reboot or normal.

**Comment by Coconutat** [comment]
> You put any first module, any, the device reboots normally .. And then there is a problem, with any reboot. At the same time, the device remembers the last task: I give the reboot command in recovery, it turns off, just turn it on, it goes into recovery ..

By the way.Can you try to use [Huawei-Creator A13](https://github.com/Iceows/huawei-creator/tree/android-13)?This can fix many GSI issues for Huawei Devices.

**Comment by Coconutat** [comment]
> Thanks for reaching out to help me figure out this issue. Unfortunately I don't have TWRP for my device on 9.0, but yours works great and does all its functions. I indicated above, on the stock firmware, there is no such problem, your kernel + your TWRP device reboots without problems, this only happens on GSI firmware .. I tried all the kernel options, installed TWRP in eRecovery and installed the stock recovery in place, the problem remains.

Android 13 GSI will cause SystemUI soft restart.Maybe you can try A10~A12.

**Comment by Coconutat** [comment]
> You put any first module, any, the device reboots normally .. And then there is a problem, with any reboot. At the same time, the device remembers the last task: I give the reboot command in recovery, it turns off, just turn it on, it goes into recovery ..

Hello,I take my P10 back.I was did some test to my phone.I flash A13 GSI(**Project Elixir**).  
I Use GSI Kernel,SELinux is Enforcing Mode.    
I will test it for a few days. Then use the modified version of Huawei Creator for comparative testing.

**Comment by Coconutat** [comment]
> Thanks for reaching out to help me figure out this issue. Unfortunately I don't have TWRP for my device on 9.0, but yours works great and does all its functions. I indicated above, on the stock firmware, there is no such problem, your kernel + your TWRP device reboots without problems, this only happens on GSI firmware .. I tried all the kernel options, installed TWRP in eRecovery and installed the stock recovery in place, the problem remains.

Maybe Use Permissive kernel is good choice.I flash gsi,the enforcing kernel will random switch to permissive mode.Use Huawei-creator only alleviate this issue, but it cannot be resolved.
