### ISSUE TITLE
KernelSU 0.6.8+ won't start

### ISSUE THREAD

**Issue by vGreatDragon** [Coconutat/android_kernel_huawei_vtr_emui9_KernelSU#7]
The Nova 2s A9.0 device does not start, it hangs on the phone screensaver. I tried both kernels and both do not start; this problem was not observed with earlier versions.

**Comment by Coconutat** [comment]
> The Nova 2s A9.0 device does not start, it hangs on the phone screensaver. I tried both kernels and both do not start; this problem was not observed with earlier versions.

Thanks for report.Please Waiting for stable version.This is pre-release.
