### ISSUE TITLE
华为P10，EMUI9.0 只有V0.5.5可以获取root权限，其他所有版本无法获取 root权限，EMUI9.1所有版本都不能获取权限。

### ISSUE THREAD

**Issue by nanmofeng** [Coconutat/android_kernel_huawei_vtr_emui9_KernelSU#8]
华为P10，EMUI9.0 只有V0.5.5可以获取root权限，其他所有版本无法获取 root权限，EMUI9.1所有版本都不能获取权限。

具体见图片，都是提示无法授权，请问怎么解决？

或者能够修复下?

谢谢！！！
![Screenshot_20231017_101826_me weishu kernelsu](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/assets/32004308/cf7dbc22-7538-4c2c-87f2-abad372c9718)

**Comment by Coconutat** [comment]
> 华为P10，EMUI9.0 只有V0.5.5可以获取root权限，其他所有版本无法获取 root权限，EMUI9.1所有版本都不能获取权限。
> 
> 具体见图片，都是提示无法授权，请问怎么解决？
> 
> 或者能够修复下?
> 
> 谢谢！！！ ![Screenshot_20231017_101826_me weishu kernelsu](https://user-images.githubusercontent.com/32004308/275693360-cf7dbc22-7538-4c2c-87f2-abad372c9718.jpg)

你更新管理器了么。内核更新也随着管理器更新。管理器去KSU项目那里下载。内核这里不提供。

**Comment by Coconutat** [comment]
> 华为P10，EMUI9.0 只有V0.5.5可以获取root权限，其他所有版本无法获取 root权限，EMUI9.1所有版本都不能获取权限。
> 
> 具体见图片，都是提示无法授权，请问怎么解决？
> 
> 或者能够修复下?
> 
> 谢谢！！！ ![Screenshot_20231017_101826_me weishu kernelsu](https://user-images.githubusercontent.com/32004308/275693360-cf7dbc22-7538-4c2c-87f2-abad372c9718.jpg)

很明显你这都是老版本管理器。  
新版本授权界面不是你这个样子。  
附图：  
![Screenshot_20231017_112312_me weishu kernelsu](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/assets/85353552/d0036342-3dd2-493f-80e2-0a1380e68680)
![Screenshot_20231017_112329_me weishu kernelsu](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/assets/85353552/5ef68624-d4a0-4f5e-a5fd-bad39bcd5717)

**Comment by nanmofeng** [comment]
哈哈，是我的错，我一直以为这个项目的管理器不更新了，就是在老版本的发布文件里的，我不知道管理器有个另外的项目。

确实是管理器没有更新到最新导致的，非常感谢解惑!
