### ISSUE TITLE
V9 Kernel doesn't have zRAM feature

### ISSUE THREAD

**Issue by Garry050** [Coconutat/android_kernel_huawei_vtr_emui9_KernelSU#9]
Before sleep, I gonna report here.

Device: MediaPad M5 8.4 (SHT-AL09)
Kernel: https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/releases/tag/Stable_v0.6.9 (Stable_KSU_Github_Action_V0.6.9+_2023.10.11)
OS: ArrowOS 13.1 Vanilla GSI (with huawei-creator patched)
SELinux: Permissive

V9 doesn't have zRAM/Swap, but V10 have it.
i checked defconfig but it's set "y" so i don't know why having that problem

https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/blob/Github_Action_Mode/arch/arm64/configs/Pangu_KSU_V9_defconfig#L1456

**Comment by Coconutat** [comment]
> Before sleep, I gonna report here.睡前，我要在这里报告。
> 
> Device: MediaPad M5 8.4 (SHT-AL09)设备： MediaPad M5 8.4 （SHT-AL09） Kernel: https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/releases/tag/Stable_v0.6.9 (Stable_KSU_Github_Action_V0.6.9+_2023.10.11)内核： https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/releases/tag/Stable_v0.6.9 （Stable_KSU_Github_Action_V0.6.9+_2023.10.11） OS: ArrowOS 13.1 Vanilla GSI (with huawei-creator patched)操作系统： ArrowOS 13.1 Vanilla GSI （with huawei-creator patched） SELinux: Permissive SELinux：宽容
> 
> V9 doesn't have zRAM/Swap, but V10 have it.V9 没有 zRAM/Swap，但 V10 有。 i checked defconfig but it's set "y" so i don't know why having that problem我检查了defconfig，但它设置为“y”，所以我不知道为什么会遇到这个问题
> 
> https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/blob/Github_Action_Mode/arch/arm64/configs/Pangu_KSU_V9_defconfig#L1456



> Before sleep, I gonna report here.
> 
> Device: MediaPad M5 8.4 (SHT-AL09) Kernel: https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/releases/tag/Stable_v0.6.9 (Stable_KSU_Github_Action_V0.6.9+_2023.10.11) OS: ArrowOS 13.1 Vanilla GSI (with huawei-creator patched) SELinux: Permissive
> 
> V9 doesn't have zRAM/Swap, but V10 have it. i checked defconfig but it's set "y" so i don't know why having that problem
> 
> https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/blob/Github_Action_Mode/arch/arm64/configs/Pangu_KSU_V9_defconfig#L1456

I have enabled ZRAM and SWAP, and in some cases, more virtual memory may be needed to ensure that the app backend is not killed. Although it may cause some performance loss.

**Comment by Coconutat** [comment]
> Before sleep, I gonna report here.
> 
> Device: MediaPad M5 8.4 (SHT-AL09) Kernel: https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/releases/tag/Stable_v0.6.9 (Stable_KSU_Github_Action_V0.6.9+_2023.10.11) OS: ArrowOS 13.1 Vanilla GSI (with huawei-creator patched) SELinux: Permissive
> 
> V9 doesn't have zRAM/Swap, but V10 have it. i checked defconfig but it's set "y" so i don't know why having that problem
> 
> https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU/blob/Github_Action_Mode/arch/arm64/configs/Pangu_KSU_V9_defconfig#L1456

I have enabled ZRAM and SWAP, and in some cases, more virtual memory may be needed to ensure that the app backend is not killed. Although it may cause some performance loss.

**Comment by Garry050** [comment]
Yes, that is true.
I just wanted to let you know that there is a disparity in kernel functionality between V9 and V10.
